# Generated by Django 2.0.4 on 2018-04-13 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DadosProduto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome do produto')),
                ('valor', models.DecimalField(decimal_places=2, default=1, max_digits=50, verbose_name='Valor do produto')),
                ('quantidade', models.IntegerField(verbose_name='Quantidade estoque')),
            ],
        ),
    ]
