# Generated by Django 2.0.4 on 2018-04-13 05:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='DadosProduto',
            new_name='DadosProdutos',
        ),
    ]
