# Generated by Django 2.0.4 on 2018-04-17 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0002_auto_20180413_0240'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dadosprodutos',
            name='valor',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=7, verbose_name='Valor do produto'),
        ),
    ]
