# Generated by Django 2.0.4 on 2018-04-17 16:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0003_auto_20180417_1244'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dadosprodutos',
            options={'verbose_name': 'Dados Produtos', 'verbose_name_plural': 'Dados Produtos'},
        ),
    ]
